
name: all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]
#  schedule:
#    - cron: '0 */1 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: 运行操作
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 安装 curl wget
        run: |
          sudo apt-get install -y curl wget

      - name: 运行脚本
        run: |
          bash ./.github/ccaeo.sh

      - name: 设置上传机器人
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
#          git config --global user.email "actions@github.com"
#          git config --global user.name "actions-user"

      - name: 添加上传文件
        run: |
          git add .
          git status
          git commit -m "$(date '+%Y年%m月%d日·周%u·%H点%M分%S秒.%3N毫秒')" -a

      - name: 上传调试日志
        uses: actions/upload-artifact@v2
        with:
          name: ccaeo.log
          path: './.ccaeo.log'

      - name: 上传文件clash
        uses: actions/upload-artifact@v2
        with:
          name: clash
          path: './clash'

      - name: 上传文件v2ray
        uses: actions/upload-artifact@v2
        with:
          name: v2ray
          path: './v2ray'

      - name: 上传文件surfboard
        uses: actions/upload-artifact@v2
        with:
          name: surfboard
          path: './surfboard'

      - name: 开始上传到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
